### ISSUE TITLE
Problems opening stream

### ISSUE THREAD

**Issue by Mrcl1450** [Applifier/unity-ads#13]
Testing ads in android logcat.

UnityAds(31007): com.unity3d.ads.android.webapp.f.b() (line:752) :: Problems opening stream: failed to connect to impact.applifier.com/127.0.0.1 (port 443) after 20000ms: isConnected failed: ECONNREFUSED (Connection refused)

UnityAds(31007): com.unity3d.ads.android.webapp.f.c() (line:820) :: Problems closing streams: null

**Comment by jannenikula** [comment]
This can happen when using Unity Ads with a rooted device and /system/etc/hosts file that resolves impact.applifier.com to 127.0.0.1. There is now a check in SDK init process that will cleanly fail init if ads are intentionally blocked. This check will be part of next public release.
