### ISSUE TITLE
Wrong argument for UnityAdsAdvertisingId.isLimitAdTrackingEnabled.invoke

### ISSUE THREAD

**Issue by AlexeiVitenko** [Applifier/unity-ads#16]
I tried to use your library. 
It seems, that you pass wrong argument to invoke method there:
https://github.com/Applifier/unity-ads/blob/master/android/sources/src/com/unity3d/ads/android/data/UnityAdsAdvertisingId.java#L63
You passed (variable Class<?> Info), instead of AdvertisingIdClient.Info instance (variable Object advertisingTrackingInfo)

**Comment by rikshot** [comment]
Good catch, thanks!
