### ISSUE TITLE
Application crashing after ad finishes.

### ISSUE THREAD

**Issue by JuanCCS** [Applifier/unity-ads#26]
My unity game is locked in portrait mode, but to view the videos clearly the user must turn their device 90 degrees in landscape mode. The problem arises when the ad finishes and the option to download the game appears. The game begins blinking weirdly and furiously. And the only way to stop this is to exit the game and close it entirely. This happens on iOS.

**Comment by jannenikula** [comment]
Issue has been reproduced and we are investigating it.

**Comment by rswlkr** [comment]
Any progress with this?

**Comment by rswlkr** [comment]
Can fix by setting default orientation to Auto Rotation and then selecting only Portrait. Take a look at this thread: http://forum.unity3d.com/threads/big-ass-bug.313037/

**Comment by JuanCCS** [comment]
Just tried it.. worked.. thanks man!

**Comment by jannenikula** [comment]
This problem was an issue in the Unity 5.0 engine. Unfortunately it took some time to find a fix but the fix should now be included in Unity 5.0.2p4 patch release. We expect that this patch release will be released next week.
