### ISSUE TITLE
NullPointerException in UnityAdsMainView constructor on Android

### ISSUE THREAD

**Issue by AndriyFliak** [Applifier/unity-ads#52]
Our app uses services and very often user will quit activity but the service will remain running. So if we call to UnityAds.init and immediately close activity via back button press activity will close and WeakReference to it in your SDK will turn to null. But because service is running UnityAds initialization will continue and will try to call the code here
https://github.com/Applifier/unity-ads/blob/master/android/sources/src/com/unity3d/ads/android/view/UnityAdsMainView.java#L52 
which leads to NullPointerException because context is null.

You can easily reproduce this issue by starting a service in your app, calling UnityAds.init and immediately closing activity

To solve this issue you need to check UnityAdsProperties.getCurrentActivity() for null here
https://github.com/Applifier/unity-ads/blob/master/android/sources/src/com/unity3d/ads/android/UnityAds.java#L1016
After that app no longer crashes 

I have about 400 of this crashes per day
Stack trace:
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	
android.view.ViewConfiguration.get (ViewConfiguration.java:359)
android.view.View. (View.java:3624)
android.view.View. (View.java:3722)
android.view.ViewGroup. (ViewGroup.java:518)
android.widget.RelativeLayout. (RelativeLayout.java:267)
android.widget.RelativeLayout. (RelativeLayout.java:263)
android.widget.RelativeLayout. (RelativeLayout.java:259)
android.widget.RelativeLayout. (RelativeLayout.java:255)
com.unity3d.ads.android.view.UnityAdsMainView. (UnityAdsMainView.java:52)
com.unity3d.ads.android.UnityAds.onWebDataCompleted (UnityAds.java:556)
com.unity3d.ads.android.webapp.UnityAdsWebData.a (UnityAdsWebData.java:677)
com.unity3d.ads.android.webapp.UnityAdsWebData.c (UnityAdsWebData.java:51)
com.unity3d.ads.android.webapp.j.onPostExecute (UnityAdsWebData.java:894)
android.os.AsyncTask.finish (AsyncTask.java:632)
android.os.Looper.loop (Looper.java:194)
android.app.ActivityThread.main (ActivityThread.java:5534)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:750)

**Comment by iamhere86** [comment]
Hi,
This is Aylin(technical account manager) from Korea office.
One of korean dev faced same issue and asked me how to solve the issue.
i would like to give him proper answer.

this commit will be applied to unityads sdk 1.4.6 version? right?
then is it ok to tell him this issue will be fixed in unityads sdk 1.4.6 version?
do you know when unityads 1.4.6 version will be released?

thanks.

**Comment by jannenikula** [comment]
Hello, thanks for reporting this. This issue has been fixed in 1.4.7 release. It is now available in the release repository.
