### ISSUE TITLE
NullPointerException in UnityAdsCacheManager.isCampaignCached on Android

### ISSUE THREAD

**Issue by AndriyFliak** [Applifier/unity-ads#54]
In some rare cases campaign is null in this function
https://github.com/Applifier/unity-ads/blob/master/android/sources/src/com/unity3d/ads/android/cache/UnityAdsCacheManager.java#L121
which leads to NullPointerException

I think checking campaign for null and returning false in that case should solve this

I was unable to reproduce this issue but I have about 300 crashes like this per day

Stack trace:
Fatal Exception: java.lang.NullPointerException 
com.unity3d.ads.android.cache.UnityAdsCacheManager.isCampaignCached (UnityAdsCacheManager.java:121)
com.unity3d.ads.android.UnityAds.onMainViewAction (UnityAds.java:462)
com.unity3d.ads.android.view.UnityAdsMainView.a (UnityAdsMainView.java:220)
com.unity3d.ads.android.view.UnityAdsMainView.onVideoPlaybackStarted (UnityAdsMainView.java:262)
com.unity3d.ads.android.video.r.run (UnityAdsVideoPlayView.java:714)
android.os.Handler.handleCallback (Handler.java:808)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5292)
java.lang.reflect.Method.invokeNative (Method.java)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by jannenikula** [comment]
Hello, thanks for reporting this. This issue has been fixed in 1.4.7 release.
