### ISSUE TITLE
iOS UIApplicationInvalidInterfaceOrientation Crash on download clicked

### ISSUE THREAD

**Issue by robertodias180** [Applifier/unity-ads#61]
My app is only landscape, and after showing a video if i click the download button the ad will rotate to portrait and crash with this error: 

*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [CustomStoreProductViewController shouldAutorotate] is returning YES'

On my other apps that have portrait orientation there is no problem.

**Comment by rasmus-unity** [comment]
Hi.

We're investigating the issue, but for now you should be able to use https://github.com/Applifier/unity-ads/commit/30acd446bdf7ecf55ad9d2c0d9d6ff963afc4cf8. Please let us know if it works, or if you see other problems with this.

Thanks,
Rasmus

**Comment by robertodias180** [comment]
i am using the  prebuilt release binaries, do you have any guide on how to use the source code. 

thanks

**Comment by robertodias180** [comment]
I was able to make it work, and it fixed the issue. Thanks :)

**Comment by robertodias180** [comment]
Fixed on 1.5.0.
